# Generated by Django 5.2.8 on 2025-11-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('gr', 'Gramo'), ('L', 'Litro'), ('unidad', 'Unidad')], default='unidad', max_length=10)),
            ],
        ),
    ]
